logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  datasource:
    url: @dataSource.url@
    username: @dataSource.user@
    password: @dataSource.password@
    hikari:
      maximum-pool-size: 4
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  messages:
    basename: messages
    fallback-to-system-locale: true

springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method
  api-docs:
    path: /api-docs

project:
  jwt:
    signKey: W27sJe29ATI7dR3juV5lWkT9WgS2C8RT
    expirationMinutes: 1440
