export const CREATE_TOURNAMENT_COMPLETED = 'tournaments/CREATE_TOURNAMENT_COMPLETED';
export const CREATE_TOURNAMENT_FAILED = 'tournaments/CREATE_TOURNAMENT_FAILED';
export const CLEAR_TOURNAMENT_ERROR = 'tournaments/CLEAR_TOURNAMENT_ERROR';
export const GET_MY_TOURNAMENTS_COMPLETED = 'tournaments/GET_MY_TOURNAMENTS_COMPLETED';
export const TOURNAMENTS_ERROR = 'tournaments/TOURNAMENTS_ERROR';
export const GET_FOLLOWED_TOURNAMENTS_COMPLETED = 'tournaments/GET_FOLLOWED_TOURNAMENTS_COMPLETED';
export const GET_ENROLLED_TOURNAMENTS_COMPLETED = 'tournaments/GET_ENROLLED_TOURNAMENTS_COMPLETED';
