export const CREATE_TOURNAMENT_COMPLETED = 'tournaments/CREATE_TOURNAMENT_COMPLETED';
export const CREATE_TOURNAMENT_FAILED = 'tournaments/CREATE_TOURNAMENT_FAILED';
export const CLEAR_TOURNAMENT_ERROR = 'tournaments/CLEAR_TOURNAMENT_ERROR';
